apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: senecacollege-org-tls
spec:
  secretName: senecacollege-org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: senecacollege.org
  dnsNames:
    - senecacollege.org
    - www.senecacollege.org